apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-example-argocd
  labels:
    app: go-example-argocd
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: go-example-argocd
  template:
    metadata:
      labels:
        app: go-example-argocd
    spec:
      imagePullSecrets:
        - name: us-east-1-ecr-registry
      containers:
        - name: go-example-argocd
          image: go-example-argocd
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      activeService: go-example-argocd
      previewService: go-example-argocd-preview