apiVersion: v1
kind: Service
metadata:
  name: golang-api-preview
  labels:
    app: golang-api
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: golang-api