apiVersion: v1
kind: Service
metadata:
  name: go-example-argocd
  labels:
    app: go-example-argocd
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: go-example-argocd