name: "Golang"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/go.yaml"
      - "src/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/go.yaml"
      - "src/**"

jobs:
  gosec:
    name: "Golang security checker"
    uses: letsrockthefuture/reusable-workflows/.github/workflows/go.yaml@main
