name: "Golang"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/golang.yaml"
      - "src/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/golang.yaml"
      - "src/**"

jobs:
  golang:
    name: "Golang"
    uses: letsrockthefuture/reusable-workflows/.github/workflows/golang.yaml@main
    with:
      language: "go"
